name: hive-metastore

services:
  hive-metastore-db:
    image: postgres:17
    container_name: hive-metastore-db
    hostname: hive-metastore-db
    environment:
      POSTGRES_USER: ${HIVE_METASTORE_USER}
      POSTGRES_PASSWORD: ${HIVE_METASTORE_PASSWORD}
      POSTGRES_DB: hive_metastore
    volumes:
      - hive-metastore-db:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${HIVE_METASTORE_USER}
      interval: 10s
      retries: 5
      start_period: 5s
    networks:
      - projeto-lakehouse
    restart: always

  hive-metastore-server:
    image: apache/hive:standalone-metastore-4.1.0  # Use a suitable Hive version
    container_name: hive-metastore-server
    hostname: hive-metastore-server
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres

    networks:
      - projeto-lakehouse
    ports:
      - mode: ingress
        target: 9083
        published: "9083"
        protocol: tcp
    depends_on:
      hive-metastore-db:
        condition: service_healthy
        required: true
    volumes:
    # precisa baixar esses arquivos e salvar na pasta hive/jars
      # - ./jars/postgresql-42.7.7.jar:/opt/hive/lib/postgresql-42.7.7.jar
      # - ./jars/hadoop-aws-3.4.0.jar:/opt/hive/lib/hadoop-aws-3.4.0.jar
      # - ./jars/bundle-2.32.25.jar:/opt/hive/lib/bundle-2.32.25.jar
      - ./conf/metastore-site.xml:/opt/hive/conf/metastore-site.xml
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  projeto-lakehouse:
    name: projeto-lakehouse
    external: true

volumes:
  hive-metastore-db:
    