name: trino

services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    container_name: trino-coordinator
    hostname: trino-coordinator
    networks:
      - projeto-lakehouse
    ports:
      - mode: ingress
        target: 9090
        published: "9090"
        protocol: "tcp"
    volumes:
      - ./trino-coordinator/etc/trino:/etc/trino
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  trino-worker-1:
    image: 'trinodb/trino:latest'
    container_name: trino-worker-1
    hostname: trino-worker-1
    networks:
      - projeto-lakehouse
    volumes:
      - ./trino-worker-1/etc/trino:/etc/trino
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  trino-worker-2:
    image: 'trinodb/trino:latest'
    container_name: trino-worker-2
    hostname: trino-worker-2
    networks:
      - projeto-lakehouse
    volumes:
      - ./trino-worker-2/etc/trino:/etc/trino
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  projeto-lakehouse:
    name: projeto-lakehouse
    external: true